openapi: 3.0.0
info:
  title: HMS
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          example: "613b6f7e9a0f2b2a2c5f9c1d"
        name:
          type: string
          example: "Pavithra Duraisamy"
        email:
          type: string
          example: "pavithra@gmail.com"
        role:
          type: string
          example: "Admin"
        password:
          type: string
          example: "pavithra@123"   
        phone:
          type: string
          example: "9672967596"
paths:
  /user/signUp:
    post:
      tags:
        - User
      summary: "Create a user"
      description: "User SignUp"
      security: []  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Pavithra Duraisamy"
                email:
                  type: string
                  example: "pavithra@gmail.com"
                role:
                  type: string
                  example: "user"
                password:
                  type: string
                  example: "pavithra@123"
                dialCode:
                  type: string
                  example: "+91"
                phone:
                  type: string
                  example: "9672967596"
      responses:
        '200':
          description: User SignUp successful
        '400':
          description: Bad request
        '409':
          description: Email already exists

  /user/login:
    post:
      tags:
        - User
      summary: signIn
      description: "User login"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "pavithra@gmail.com"
                password:
                  type: string
                  example: "pavithra@123"
      responses:
        '200':
          description: Successful login

        '400':
          description: Bad request - User not found or Incorrect credential

        '500':
          description: Internal Server Error
 

/user/viewProfile:
    get:
      tags:
        - User
      summary: View Profile
      description: "Get the profile of the logged-in user"
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized - Token is missing or invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
