openapi: 3.0.0
info:
  title: HMS Password Management API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UpdatePasswordRequest:
      type: object
      properties:
        password:
          type: string
          example: "newSecurePassword123"
    ForgotPasswordLinkRequest:
      type: object
      properties:
        email:
          type: string
          example: "user@example.com"
    ResetPasswordRequest:
      type: object
      properties:
        existingPassword:
          type: string
          example: "currentPassword123"
        newPassword:
          type: string
          example: "newSecurePassword123"
        confirmNewPassword:
          type: string
          example: "newSecurePassword123"

paths:
  /password/update_password/{key}:
    post:
      tags:
        - Password
      summary: forget password
      description: Update the user password using a unique key.
      security: []  
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
            example: "someUniqueKey"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePasswordRequest'
      responses:
        '200':
          description: Password updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Password updated successfully
        '400':
          description: Bad request
        '404':
          description: Key not found
        '500':
          description: Internal Server Error

  /password/send_forgot_password_link:
    post:
      tags:
        - Password
      summary: Send Forgot Password Link
      description: Send a forgot password link to the user's email.
      security: []  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordLinkRequest'
      responses:
        '200':
          description: Forgot password link sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Forgot password link sent successfully
        '400':
          description: Bad request
        '404':
          description: User not found
        '500':
          description: Internal Server Error

  /password/reset_password:
    post:
      tags:
        - Password
      summary: Reset Password
      description: Reset the password for the authenticated user.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        '200':
          description: Password reset successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Password reset successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
